classDiagram
class AudienceSyncStepBase
AudienceSyncStepBase : static TYPE_NAME
AudienceSyncStepBase : get_client()
AudienceSyncStepBase : create_audience()
AudienceSyncStepBase : advance_after_exhausting_retries?()
AudienceSyncStepBase : execute()
AudienceSyncStepBase : redis_key()
AudienceSyncStepBase : get_base_step_object()
AudienceSyncStepBase : get_step_with_redis_key()
AudienceSyncStepBase : custom_audience_id <String>
AudienceSyncStepBase : custom_audience_name <String>
AudienceSyncStepBase : action <String>
AudienceSyncStepBase : fields_to_match <Array>
AudienceSyncStepBase : intent <String>

class Action
Action : static ADD_USERS
Action : static REMOVE_USERS

class Intent
Intent : static CREATE_NEW
Intent : static SYNC_TO_EXISTING

Action <.. AudienceSyncStepBase
Intent <.. AudienceSyncStepBase
